name: SPS
channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.5=py311h459d7ec_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h459d7ec_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.7.22=hcc3641f_8
  - aws-c-cal=0.7.0=h816f305_0
  - aws-c-common=0.9.23=h4ab18f5_0
  - aws-c-compression=0.2.18=he027950_7
  - aws-c-event-stream=0.4.2=h7671281_15
  - aws-c-http=0.8.2=h9eec0b2_5
  - aws-c-io=0.14.10=h98aea76_0
  - aws-c-mqtt=0.10.4=hcd6a914_8
  - aws-c-s3=0.6.0=h30b82e7_1
  - aws-c-sdkutils=0.1.16=he027950_3
  - aws-checksums=0.1.18=he027950_7
  - aws-crt-cpp=0.27.3=h55c4308_1
  - aws-sdk-cpp=1.11.329=h46c3b66_9
  - azure-core-cpp=1.12.0=h830ed8b_0
  - azure-identity-cpp=1.8.0=hdb0d106_1
  - azure-storage-blobs-cpp=12.11.0=ha67cba7_1
  - azure-storage-common-cpp=12.6.0=he3f277c_1
  - azure-storage-files-datalake-cpp=12.10.0=h29b5301_1
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - blosc=1.21.6=hef167b5_0
  - bokeh=3.4.2=pyhd8ed1ab_0
  - branca=0.7.2=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py311hb755f60_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.32.1=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.7.4=py311h06a4308_0
  - cffi=1.16.0=py311hb3a22ac_0
  - cfitsio=4.3.0=hbdc6101_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorcet=3.1.0=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py311h9547e67_0
  - cucim=24.06.00=cuda12_py311_240605_ga383154_0
  - cuda-cccl=12.4.127=0
  - cuda-crt-dev_linux-64=12.2.140=ha770c72_1
  - cuda-crt-tools=12.2.140=ha770c72_1
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-nvcc-dev_linux-64=12.2.140=ha770c72_1
  - cuda-nvcc-impl=12.2.140=hd3aeb46_1
  - cuda-nvcc-tools=12.2.140=hd3aeb46_1
  - cuda-nvrtc=12.4.127=0
  - cuda-nvvm-dev_linux-64=12.2.140=ha770c72_1
  - cuda-nvvm-impl=12.2.140=h59595ed_1
  - cuda-nvvm-tools=12.2.140=h59595ed_1
  - cuda-profiler-api=12.4.127=0
  - cuda-python=12.5.0=py311hc0c7bc8_0
  - cuda-version=12.2=he2b69de_3
  - cudf=24.06.01=cuda12_py311_240702_g4e59b79cf3_0
  - cudf_kafka=24.06.01=cuda12_py311_240702_g4e59b79cf3_0
  - cugraph=24.06.01=cuda12_py311_240613_g6a411dca4_0
  - cuml=24.06.01=cuda12_py311_240612_gbbd19ab82_0
  - cuproj=24.06.00=cuda12_py311_240605_g3ffcc894_0
  - cupy=13.2.0=py311he5a987b_0
  - cupy-core=13.2.0=py311h3bdf873_0
  - cuspatial=24.06.00=cuda12_py311_240605_g3ffcc894_0
  - custreamz=24.06.01=cuda12_py311_240702_g4e59b79cf3_0
  - cuvs=24.06.00=cuda12_py311_240605_g2a2c433_0
  - cuxfilter=24.06.00=cuda12_py311_240605_gda4611c_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - cytoolz=0.12.3=py311h459d7ec_0
  - dask=2024.5.1=pyhd8ed1ab_0
  - dask-core=2024.5.1=pyhd8ed1ab_0
  - dask-cuda=24.06.00=py311_240605_g2fc151b_0
  - dask-cudf=24.06.01=cuda12_py311_240702_g4e59b79cf3_0
  - dask-expr=1.1.1=pyhd8ed1ab_1
  - datashader=0.16.3=pyhd8ed1ab_0
  - debugpy=1.8.2=py311h4332511_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2024.5.1=pyhd8ed1ab_0
  - distributed-ucxx=0.38.00=py3.11_240605_ged922d2_0
  - dlpack=0.8=h59595ed_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.2=h6a678d5_0
  - fastrlock=0.8.2=py311hb755f60_2
  - fmt=10.2.1=h00ab1b0_0
  - folium=0.17.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py311h61187de_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - freexl=2.0.0=h743c826_0
  - frozenlist=1.4.1=py311h459d7ec_0
  - fsspec=2024.6.1=pyhff2d567_0
  - gdal=3.7.2=py311h815a124_5
  - geopandas=1.0.1=pyhd8ed1ab_0
  - geopandas-base=1.0.1=pyha770c72_0
  - geos=3.12.0=h59595ed_0
  - geotiff=1.7.1=hee599c5_13
  - gettext=0.22.5=h59595ed_2
  - gettext-tools=0.22.5=h59595ed_2
  - gflags=2.2.2=he1b5a44_1004
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - hdf4=4.2.15=h501b40f_6
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - holoviews=1.19.1=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.7=pyhd8ed1ab_0
  - imagecodecs-lite=2019.12.3=py311h18e1886_8
  - imageio=2.34.2=pyh12aca89_0
  - importlib-metadata=8.0.0=pyha770c72_0
  - importlib_metadata=8.0.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.26.0=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - json-c=0.17=h1220068_1
  - jsonpointer=3.0.0=py311h38be061_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-server-proxy=4.3.0=pyhd8ed1ab_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h38be061_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - kealib=1.5.3=hee9dde6_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py311h9547e67_1
  - krb5=1.21.3=h659f571_0
  - lazy_loader=0.4=pyhd8ed1ab_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.4=hfca40fe_0
  - libarrow=16.1.0=h34456a7_14_cpu
  - libarrow-acero=16.1.0=he02047a_14_cpu
  - libarrow-dataset=16.1.0=he02047a_14_cpu
  - libarrow-substrait=16.1.0=hc9a23c6_14_cpu
  - libasprintf=0.22.5=h661eb56_2
  - libasprintf-devel=0.22.5=h661eb56_2
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcucim=24.06.00=cuda12_240605_ga383154_0
  - libcudf=24.06.01=cuda12_240702_g4e59b79cf3_0
  - libcudf_kafka=24.06.01=cuda12_240702_g4e59b79cf3_0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcugraph=24.06.01=cuda12_240613_g6a411dca4_0
  - libcugraph_etl=24.06.01=cuda12_240613_g6a411dca4_0
  - libcugraphops=24.06.00=cuda12_240605_g3682e739_0
  - libcuml=24.06.01=cuda12_240612_gbbd19ab82_0
  - libcumlprims=24.06.00=cuda12_240605_gfa5d8ef_0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.8.0=hca28451_1
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libcuspatial=24.06.00=cuda12_240605_g3ffcc894_0
  - libcuvs=24.06.00=cuda12_240605_g2a2c433_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=14.1.0=h77fa898_0
  - libgdal=3.7.2=h6238fc3_5
  - libgettextpo=0.22.5=h59595ed_2
  - libgettextpo-devel=0.22.5=h59595ed_2
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=14.1.0=h77fa898_0
  - libgoogle-cloud=2.26.0=h26d7fe4_0
  - libgoogle-cloud-storage=2.26.0=ha262f82_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - libkml=1.3.0=hbbc8833_1020
  - libkvikio=24.06.00=cuda12_240605_gd3f15ec_0
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnetcdf=4.9.2=nompi_h135f659_114
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libnvjpeg=12.3.1.117=0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libparquet=16.1.0=h9e5060d_14_cpu
  - libpng=1.6.43=h2797004_0
  - libpq=16.3=ha72fbe1_0
  - libprotobuf=4.25.3=h08a7969_0
  - libraft=24.06.00=cuda12_240605_g63a506d3_0
  - libraft-headers=24.06.00=cuda12_240605_g63a506d3_0
  - libraft-headers-only=24.06.00=cuda12_240605_g63a506d3_0
  - librdkafka=1.9.2=ha5a0de0_2
  - libre2-11=2023.09.01=h5a48ba9_2
  - librmm=24.06.00=cuda12_240605_gd889275f_0
  - librttopo=1.1.0=hb58d41b_14
  - libsodium=1.0.18=h7b6447c_0
  - libspatialite=5.1.0=h090f1da_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h29866fb_1
  - libucxx=0.38.00=cuda12_240605_ged922d2_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.0.3=rapidsai_h9aa48e0_5
  - libxml2=2.12.7=h4c95cb1_3
  - libzip=1.10.1=h2629f0a_3
  - libzlib=1.3.1=h4ab18f5_1
  - linkify-it-py=2.0.3=pyhd8ed1ab_0
  - llvmlite=0.43.0=py311hbde99c3_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311h38e4bf4_0
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mapclassify=2.6.1=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py311h459d7ec_0
  - matplotlib-base=3.9.1=py311hffb96ce_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - minizip=4.0.7=h401b404_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - msgpack-python=1.0.8=py311h52f7536_0
  - multidict=6.0.5=py311h459d7ec_0
  - multipledispatch=0.6.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nccl=2.22.3.1=hbc370b7_0
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - nodejs=22.4.1=h6d9b948_0
  - nspr=4.35=h27087fc_0
  - nss=3.102=h593d115_0
  - numba=0.60.0=py311h4bc866e_0
  - numpy=1.26.4=py311h64a7726_0
  - nvcomp=3.0.6=h10b603f_0
  - nvtx=0.2.10=py311h459d7ec_0
  - nx-cugraph=24.06.01=py311_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4ab18f5_1
  - orc=2.0.1=h17fec99_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py311h14de704_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=1.4.4=pyhd8ed1ab_0
  - param=2.1.1=pyhff2d567_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311h8aef010_1
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.2=pyhd8ed1ab_0
  - poppler=23.08.0=hf2349cb_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=16.3=h8e811e2_0
  - proj=9.3.0=h1d62c97_2
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - prompt_toolkit=3.0.47=hd8ed1ab_0
  - psutil=6.0.0=py311h331c9d8_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=2.0.3=rapidsai_pyh6c689ce_5
  - pyarrow=16.1.0=py311hbd00459_4
  - pyarrow-core=16.1.0=py311h8c3dac4_4_cpu
  - pyarrow-hotfix=0.6=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyct=0.5.0=pyhd8ed1ab_0
  - pyee=8.1.0=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pylibcugraph=24.06.01=cuda12_py311_240613_g6a411dca4_0
  - pylibraft=24.06.00=cuda12_py311_240605_g63a506d3_0
  - pynvjitlink=0.3.0=py311hd269673_0
  - pynvml=11.4.1=pyhd8ed1ab_0
  - pyogrio=0.7.2=py311hbac4ec9_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyppeteer=1.0.2=pyhd8ed1ab_0
  - pyproj=3.6.1=py311h1facc83_4
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.9=hb806964_0_cpython
  - python-confluent-kafka=1.9.2=py311hd4cff14_2
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyviz_comms=3.0.2=pyhd8ed1ab_1
  - pywavelets=1.6.0=py311h18e1886_0
  - pyyaml=6.0.1=py311h459d7ec_1
  - pyzmq=26.0.3=py311h08a0b41_0
  - qhull=2020.2=h434a139_5
  - raft-dask=24.06.00=cuda12_py311_240605_g63a506d3_0
  - rapids=24.06.00=cuda12_py311_240605_g9ea7562_0
  - rapids-dask-dependency=24.06.00=py_0
  - rapids-xgboost=24.06.00=cuda12_py311_240605_g9ea7562_0
  - rdma-core=52.0=he02047a_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rmm=24.06.00=cuda12_py311_240605_gd889275f_0
  - rpds-py=0.19.0=py311hb3a8bbb_0
  - s2n=1.4.17=he19d79f_0
  - scikit-image=0.20.0=py311h2872171_1
  - scikit-learn=1.5.1=py311hd632256_0
  - scipy=1.14.0=py311h517d4fd_1
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=70.3.0=pyhd8ed1ab_0
  - shapely=2.0.2=py311he06c224_0
  - simpervisor=1.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=ha2e4443_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.12.0=hd2e6256_2
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - streamz=0.6.4=pyh6c4a22f_0
  - tblib=3.0.0=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2020.6.3=py_0
  - tiledb=2.16.3=hf0b6e87_3
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=0.12.1=pyhd8ed1ab_0
  - tornado=6.4.1=py311h331c9d8_0
  - tqdm=4.66.4=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - treelite=4.1.2=py311he8f9275_2
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_0
  - ucx=1.15.0=hda83522_8
  - ucx-proc=1.0.0=gpu
  - ucx-py=0.38.00=py311_240605_g8e99eaf_0
  - ucxx=0.38.00=cuda12_py3.11_240605_ged922d2_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=1.26.19=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webcolors=24.6.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - websockets=10.4=py311hd4cff14_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xarray=2024.6.0=pyhd8ed1ab_1
  - xerces-c=3.2.5=hac6953d_0
  - xgboost=2.0.3=rapidsai_pyhba369c9_5
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyzservices=2024.6.0=pyhd8ed1ab_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py311h459d7ec_0
  - zeromq=4.3.5=h6a678d5_0
  - zict=3.0.0=pyhd8ed1ab_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.3.1=h4ab18f5_1
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/jibby2k1/miniconda3/envs/SPS
